code --install-extension 844196.vscode-php-symbol-rename
&& code --install-extension anseki.vscode-color
&& code --install-extension artlaman.chalice-color-theme
&& code --install-extension bmewburn.vscode-intelephense-client
&& code --install-extension CoenraadS.bracket-pair-colorizer-2
&& code --install-extension esbenp.prettier-vscode
&& code --install-extension felixfbecker.php-debug
&& code --install-extension GitHub.vscode-pull-request-github
&& code --install-extension goessner.mdmath
&& code --install-extension humao.rest-client
&& code --install-extension IBM.output-colorizer
&& code --install-extension icrawl.discord-vscode
&& code --install-extension James-Yu.latex-workshop
&& code --install-extension JoeBerria.statusbarerror
&& code --install-extension jprestidge.theme-material-theme
&& code --install-extension lamartire.git-indicators
&& code --install-extension mechatroner.rainbow-csv
&& code --install-extension mhmadhamster.postcss-language
&& code --install-extension ms-azuretools.vscode-docker
&& code --install-extension ms-python.python
&& code --install-extension piotrpalarz.vscode-gitignore-generator
&& code --install-extension PKief.material-icon-theme
&& code --install-extension pranaygp.vscode-css-peek
&& code --install-extension redhat.java
&& code --install-extension redhat.vscode-yaml
&& code --install-extension ritwickdey.LiveServer
&& code --install-extension srmeyers.git-prefix
&& code --install-extension steoates.autoimport
&& code --install-extension vittorioromeo.expand-selection-to-scope
&& code --install-extension vscjava.vscode-java-debug
&& code --install-extension vscjava.vscode-java-dependency
&& code --install-extension wix.vscode-import-cost
&& code --install-extension xabikos.JavaScriptSnippets
&& code --install-extension Zignd.html-css-class-completion
