code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension steoates.autoimport
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension artlaman.chalice-color-theme
code --install-extension anseki.vscode-color
code --install-extension pranaygp.vscode-css-peek
code --install-extension vscjava.vscode-java-debug
code --install-extension icrawl.discord-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension vittorioromeo.expand-selection-to-scope
code --install-extension lamartire.git-indicators
code --install-extension srmeyers.git-prefix
code --install-extension github.vscode-pull-request-github
code --install-extension wix.vscode-import-cost
code --install-extension zignd.html-css-class-completion
code --install-extension vscjava.vscode-java-dependency
code --install-extension xabikos.javascriptsnippets
code --install-extension redhat.java
code --install-extension james-yu.latex-workshop
code --install-extension ritwickdey.liveserver
code --install-extension goessner.mdmath
code --install-extension pkief.material-icon-theme
code --install-extension ibm.output-colorizer
code --install-extension felixfbecker.php-debug
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension 844196.vscode-php-symbol-rename
code --install-extension mhmadhamster.postcss-language
code --install-extension esbenp.prettier-vscode
code --install-extension ms-python.python
code --install-extension mechatroner.rainbow-csv
code --install-extension humao.rest-client
code --install-extension joeberria.statusbarerror
code --install-extension jprestidge.theme-material-theme
code --install-extension redhat.vscode-yaml
