code --install-extension 844196.vscode-php-symbol-rename
&& code --install-extension bmewburn.vscode-intelephense-client
&& code --install-extension CoenraadS.bracket-pair-colorizer-2
&& code --install-extension esbenp.prettier-vscode
&& code --install-extension eserozvataf.one-dark-pro-monokai-darker
&& code --install-extension felixfbecker.php-debug
&& code --install-extension GitHub.vscode-pull-request-github
&& code --install-extension goessner.mdmath
&& code --install-extension IBM.output-colorizer
&& code --install-extension icrawl.discord-vscode
&& code --install-extension James-Yu.latex-workshop
&& code --install-extension JoeBerria.statusbarerror
&& code --install-extension jprestidge.theme-material-theme
&& code --install-extension mechatroner.rainbow-csv
&& code --install-extension ms-azuretools.vscode-docker
&& code --install-extension ms-python.python
&& code --install-extension ms-python.vscode-pylance
&& code --install-extension ms-vscode.cpptools
&& code --install-extension PKief.material-icon-theme
&& code --install-extension pranaygp.vscode-css-peek
&& code --install-extension redhat.vscode-yaml
&& code --install-extension srmeyers.git-prefix
&& code --install-extension Zignd.html-css-class-completion
